lsi: false
safe: true
source: github.com/pranoy-mathur/pranoy-mathur.github.io/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minima
